name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn dist

      - name: List files in dist
        run: ls -la dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-macos
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download macOS build artifacts
        uses: actions/download-artifact@v2
        with:
          name: electron-app-macos
          path: dist

      - name: List files in dist
        run: ls -la dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          token: ${{ secrets.GH_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          name: casbin-editor-macos.zip
          content_type: application/zip
